apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
endpoint: grpc.jumpstarter.192.168.0.203.nip.io:8082
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2p1bXBzdGFydGVyLmRldi9jb250cm9sbGVyIiwic3ViIjoiNDk2OWIwNzctZWZkOS00MTI3LTk4OTctYTc5ZWZhZTczNDI5IiwiYXVkIjpbImh0dHBzOi8vanVtcHN0YXJ0ZXIuZGV2L2NvbnRyb2xsZXIiXSwibmJmIjoxNzMzODQ1MDk4LCJpYXQiOjE3MzM4NDUwOTgsImp0aSI6IjFhNmU3OTY4LTdlM2YtNGFlOC1iMjJhLWZlNjM4OWY2OTliOCIsImt1YmVybmV0ZXMuaW8va2luZCI6IkV4cG9ydGVyIiwia3ViZXJuZXRlcy5pby9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vdWlkIjoiNDk2OWIwNzctZWZkOS00MTI3LTk4OTctYTc5ZWZhZTczNDI5Iiwia3ViZXJuZXRlcy5pby9hcGlfdmVyc2lvbiI6Imp1bXBzdGFydGVyLmRldi92MWFscGhhMSJ9.E72JZxmiBN6zZUw4z1vmr1Map_T6fYLJ80edsWv7iX4
export:
  serial:
    type: "jumpstarter.drivers.pyserial.driver.PySerial"
    config:
      url: "/dev/ttyUSB0"
      baudrate: 1843200
  power:
    type: jumpstarter.drivers.power.driver.MockPower
  tftp:
    type: jumpstarter_driver_tftp.driver.TftpServer
    config:
      root_dir: "/var/lib/tftpboot/"
      host: "192.168.1.111"
      port: 6969
